name: Docker Hub README & description sync
description: Sync README.md and description from Github to Docker Hub
author: 'Damian Mee <spam@meedamian.com>'
inputs:
  user:
    description: Docker Hub username.  Set only if different than on Github.
    required: false

  pass:
    description: Docker Hub password
    required: true

  slug:
    description: |
      Docker Hub repository path in the form of: <namespace>/<name>.  Gets converted to lower case.
      Only needed, if different than Github's.
    required: false

  readme:
    description: Optional relative path to the README.md file.  If not provided, one at repo root used.
    required: false

  description:
    description: |
      Docker Hub repo's short description to set.  If set to just `true`, Github's desription is used.
      If omitted, no action is performed.
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  color: 'green'
  icon: 'target'
